name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.6+10
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.6+10
      - name: Run Coverage
        run: |
          chmod +x mvn clean test

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: https://github.com/pcroch/address-book/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
